name: Ios build

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Cocoapod dependencies
        run: |
          cd ./ios
          pod install

      - name: Build ios
        run: |
          xcodebuild -workspace ios/rntest.xcworkspace \
          -configuration Release \
          -scheme "rntest" \
          -destination "platform=iOS Simulator,name=iPhone 14" \
          clean build

      # - name: Run tests
      #   run: xcodebuild test -scheme MyProjectName -project MyProjectName.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}

  # release:
  #   if: startsWith(github.ref, 'refs/tags/')
  #   name: package
  #   runs-on: macos-latest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: Mobile
  #     - run: mkdir release && cp ./app-release.ipa release

  # publish:
  #   name: publish
  #   runs-on: ubuntu-latest
  #   needs: [release]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Download signed APK
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: Mobile.apk

  #     - name: Display structure of downloaded files
  #       run: ls -R
